### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by ygator** [badzz/wd03-utils#1]
What are the prerequisites to use this?  From the source it looks like the package kmod-i2c-ralink is needed.  Are there any others?  Does the /dev/i2c-0 device need to be manually created as it is not showing up for me after I installed kmod-i2c-ralink?  All I see in dmesg about i2c is:
`[   17.316092] i2c /dev entries driver`

Thanks

**Comment by badzz** [comment]
hi

current stable release of openwrt do not have i2c activated on the wd03 

cat /sys/firmware/devicetree/base/palmbus@10000000/i2c@900#/status
will show disabled
Howeever the current unstable is not booting for me. I need to check why
thx

**Comment by ygator** [comment]
What needs to be enabled to get i2c working?  I have a build environment that I think works, but I don't see any relevant options in menuconfig.

In the end I think this should be enabled in official builds.

**Comment by badzz** [comment]
Here is the commit that enable it
It is only in snapshot and not in the stable build
https://github.com/openwrt/openwrt/commit/52809db5446e1c4fbdaa50b703961d036c14bceb#diff-14ad87783c7196e48d0431921e61e9bc

**Comment by ygator** [comment]
I built 18.06.1 with WD03.dts changed and the packages kmod-i2c-core and kmod-i2c-ralink built in.  I then built wd03-battery and was able to run it.

Thanks.
